// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";

dotenv.config({ path: "config.env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
    schema: "src/",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: process.env.DATABASE_URL,
    },
});
